In [2]:
import numpy as np

In [6]:
#1
x = np.array([1, 2, 3])
y = np.array([[9, 8, 7], [6, 5, 4]])
z = np.array([2,3,4])
a1 = np.vstack([x, y])
print(a1)
a2 = np.hstack([x, z])
print(a2)

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[1 2 3 2 3 4]


In [7]:
#2
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])
intersection_set = set(A).intersection(B)
common_elements = np.array(list(intersection_set))
print("Common Elements:", common_elements)

Common Elements: [3 4 5]


In [8]:
#3
A = np.array([2, 6, 8, 3, 10, 12, 7, 5])
mask = (A >= 5) & (A <= 10)
filtered_elements = A[mask]
print("Elements within the range:", filtered_elements)

Elements within the range: [ 6  8 10  7  5]


In [9]:
#4
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])
petal_length_condition = iris_2d[:, 2] > 1.5
sepal_length_condition = iris_2d[:, 0] < 5.0
filtered_rows = iris_2d[petal_length_condition & sepal_length_condition]
print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [11]:
import pandas as pd

In [12]:
#1
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_data = df.iloc[::20, [0, 2, 4]]
print(filtered_data)

   Manufacturer     Type  Price
0         Acura    Small   15.9
20     Chrysler  Compact   15.8
40        Honda   Sporty   19.8
60      Mercury  Midsize   14.9
80       Subaru    Small   10.9


In [13]:
#2
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()
df['Min.Price'].fillna(min_price_mean, inplace=True)
df['Max.Price'].fillna(max_price_mean, inplace=True)
print(df)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [16]:
#3
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)
row_sums = df.sum(axis=1)
print(row_sums)
rows_with_sum_gt_100 = df[row_sums > 100]
print(rows_with_sum_gt_100)

     0   1   2   3
0   14  23  22  28
1   13  27  24  33
2   39  17  31  29
3   19  12  37  24
4   21  22  26  17
5   15  27  15  20
6   16  26  23  22
7   20  28  19  13
8   18  21  30  36
9   33  10  36  38
10  37  31  28  37
11  22  11  22  29
12  36  24  39  22
13  25  16  38  15
14  37  19  21  31
0      87
1      97
2     116
3      92
4      86
5      77
6      87
7      80
8     105
9     117
10    133
11     84
12    121
13     94
14    108
dtype: int64
     0   1   2   3
2   39  17  31  29
8   18  21  30  36
9   33  10  36  38
10  37  31  28  37
12  36  24  39  22
14  37  19  21  31
